/* Three-step VibeGuys product submission workspace with live media previews. */
(()=>{
  const copy={
    title:['제품 등록하기','Submit your product'],
    intro1:['당신이 만든 멋진 서비스를 VibeGuys에 소개하세요.','Introduce the product you built to VibeGuys.'],
    intro2:['정확한 정보는 더 좋은 발견과 연결을 만듭니다.','Accurate information leads to better discovery and connections.'],
    step1:['기본 정보 & 이미지','Basics & images'],step2:['상세 정보 & 링크','Details & links'],step3:['최종 확인','Final check'],
    basics:['기본 정보','Basic information'],details:['상세 정보 & 링크','Product details & links'],review:['최종 확인','Final check'],
    productName:['제품 이름','Product name'],tagline:['한 줄 소개','One-line description'],category:['카테고리','Category'],platform:['제품 타입','Product type'],status:['상태','Status'],description:['설명','Description'],audience:['대상 사용자','Target audience'],problem:['해결하는 문제','Problem it solves'],tags:['태그 (최대 5개)','Tags (up to 5)'],
    namePlaceholder:['예) VIBEGUYS','e.g. VIBEGUYS'],tagPlaceholder:['예) 쏟아지는 바이브 속, 제대로 된 제품을 고르는 디렉터리','e.g. A curated directory for finding the good products in a flood of vibes'],categoryPlaceholder:['카테고리를 선택하세요','Select a category'],descriptionPlaceholder:['예) VIBEGUYS가 어떤 제품이고 누구에게 필요한지 구체적으로 설명해주세요.','e.g. Explain what VIBEGUYS does and who it is for.'],audiencePlaceholder:['예) 새로운 웹과 앱을 빠르게 발견하고 싶은 사람','e.g. People looking for useful new web and app products'],problemPlaceholder:['예) 매일 쏟아지는 서비스 중 쓸 만한 제품을 찾기 어렵습니다.','e.g. It is hard to find worthwhile products among daily launches.'],tagsPlaceholder:['예) 바이브코딩, 제품 탐색, 웹, 앱','e.g. vibe coding, discovery, web, app'],
    web:['웹','Web'],app:['앱','App'],both:['웹 + 앱','Web + App'],released:['출시됨','Released'],beta:['베타','Beta'],development:['개발 중','In development'],idea:['아이디어 단계','Idea stage'],choiceRequired:['제품 타입과 상태를 선택해주세요.','Choose a product type and status.'],
    creator:['제작자 이름','Creator name'],website:['웹사이트 URL','Website URL'],launchDate:['출시일','Launch date'],languages:['지원 언어','Supported languages'],contact:['연락 이메일','Contact email'],creatorPlaceholder:['예) VIBEGUYS TEAM','e.g. VIBEGUYS TEAM'],languagePlaceholder:['예) 한국어, English','e.g. Korean, English'],
    logoImage:['로고 이미지','Logo image'],logoHelp:['정사각형 PNG, JPG 또는 WEBP · 최대 6MB','Square PNG, JPG, or WEBP · up to 6MB'],projectImages:['프로젝트 이미지','Project images'],projectImagesHelp:['가로형 실제 화면을 최대 6장까지 추가하세요.','Add up to 6 landscape product screenshots.'],addLogo:['로고 추가','Add logo'],addProjectImage:['이미지 추가','Add image'],dropLogo:['클릭하거나 로고를 여기에 드롭하세요.','Click or drop your logo here.'],dropProjectImages:['클릭하거나 프로젝트 이미지를 여기에 드롭하세요.','Click or drop project images here.'],remove:['삭제','Remove'],invalidImage:['PNG, JPG, WEBP 또는 GIF 이미지(장당 최대 6MB)만 첨부할 수 있습니다.','Attach PNG, JPG, WEBP, or GIF images up to 6MB each.'],imageLimit:['프로젝트 이미지는 최대 6장까지 첨부할 수 있습니다.','You can attach up to 6 project images.'],
    docs:['문서 링크','Documentation link'],demo:['데모 영상','Demo video'],github:['GitHub 링크','GitHub link'],
    agreement:['피싱·악성코드·인증정보 수집을 금지하며 등록물의 법적 책임, 자동 보안 사전검사와 관리자 검토 정책에 동의합니다.','I prohibit phishing, malware, and credential harvesting and accept legal responsibility, automated security checks, and administrator review.'],
    previous:['이전','Back'],next:['다음 단계','Next step'],submit:['SUBMIT','SUBMIT'],
    preview:['미리보기','Preview'],previewHelp:['입력과 첨부 내용이 실시간으로 반영됩니다.','Your text and uploads appear here in real time.'],visit:['웹사이트 방문','Visit website'],features:['주요 정보','Key information'],links:['링크','Links'],websiteLink:['웹사이트','Website'],docsLink:['문서','Docs'],demoLink:['데모 영상','Demo video'],githubLink:['GitHub','GitHub'],security:['등록 전 자동 보안 검사와 운영진 검토가 진행됩니다.','An automated security check and administrator review run before publishing.'],emptyImages:['프로젝트 이미지 미리보기','Project image preview'],emptyFeatures:['입력한 대상 사용자, 해결 문제와 태그가 여기에 표시됩니다.','Your audience, problem, and tags will appear here.'],
    guide:['가이드','Guide'],guideAccuracy:['정확한 정보','Accurate information'],guideAccuracyBody:['정확할수록 사용자에게 더 잘 발견돼요.','Better information makes your product easier to discover.'],guideShots:['프로젝트 이미지','Project images'],guideShotsBody:['실제 화면은 최소 3장 이상 등록해주세요.','Add at least three real product screenshots.'],guideLinks:['링크 확인','Link verification'],guideLinksBody:['모든 링크는 제출 후 자동으로 확인됩니다.','Every submitted link is checked automatically.'],guideReview:['검토 과정','Review process'],guideReviewBody:['자동 보안 검사 후 운영진 검토가 진행됩니다.','Administrator review follows the automated security check.'],help:['도움이 필요하신가요?','Need help?'],helpBody:['등록 가이드를 확인하거나 문의하세요.','Read the submission guide or contact us.'],openGuide:['가이드 보기','View guide'],
    reviewIntro:['입력한 내용을 마지막으로 확인한 뒤 제출하세요. 제출 즉시 자동 보안 검사와 운영진 검토가 시작됩니다.','Check your details and submit. Automated security and administrator review begin immediately.'],reviewProduct:['제품','Product'],reviewType:['유형','Type'],reviewUrl:['웹사이트','Website'],reviewMedia:['프로젝트 이미지','Project images']
  };
  const categories=[['AI','AI 도구','AI Tools'],['Productivity','생산성','Productivity'],['Design','디자인','Design'],['Developer Tools','개발 도구','Developer Tools'],['Finance','금융','Finance'],['Marketing','마케팅','Marketing'],['Education','교육','Education'],['Lifestyle','라이프스타일','Lifestyle'],['Games','게임','Games'],['Utilities','유틸리티','Utilities']];
  const allowedImageTypes=new Set(['image/jpeg','image/png','image/webp','image/gif']);
  const maxImageBytes=6*1024*1024;
  let currentHost=null,currentStep=1,logoFile=null,projectFiles=[],logoObjectUrl='',projectObjectUrls=[];
  const isKo=()=>document.documentElement.lang==='ko';
  const t=key=>copy[key]?.[isKo()?0:1]||key;
  const esc=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const text=(tag,key)=>`<${tag} data-submit-copy="${key}">${esc(t(key))}</${tag}>`;
  function choice(name,value,label,extra=''){return `<button type="button" class="submit-choice" data-submit-choice="${name}" data-value="${value}" ${extra}><span data-submit-copy="${label}">${esc(t(label))}</span></button>`}
  function clearObjectUrls(){if(logoObjectUrl)URL.revokeObjectURL(logoObjectUrl);projectObjectUrls.forEach(url=>URL.revokeObjectURL(url));logoObjectUrl='';projectObjectUrls=[]}

  function render(host){
    if(!host)return;clearObjectUrls();currentHost=host;currentStep=1;logoFile=null;projectFiles=[];document.body.dataset.activeView='submit';
    const categoryOptions=categories.map(([value,ko,en])=>`<option value="${value}">${esc(isKo()?ko:en)}</option>`).join('');
    host.innerHTML=`<section class="submit-page"><div class="submit-layout">
      <form class="submit-form-column" id="submit-form">
        <header class="submit-heading">${text('h1','title')}<p><span data-submit-copy="intro1">${esc(t('intro1'))}</span><br><span data-submit-copy="intro2">${esc(t('intro2'))}</span></p></header>
        <ol class="submit-steps" aria-label="${esc(t('title'))}">${[1,2,3].map(index=>`<li class="${index===1?'active':''}" data-submit-step-indicator="${index}"><b>${index}</b><span data-submit-copy="step${index}">${esc(t(`step${index}`))}</span></li>`).join('')}</ol>
        <input type="hidden" name="listing_type" value="live">
        <section class="submit-step-panel" data-submit-step="1">${text('h2','basics')}<div class="submit-field-grid">
          <div class="submit-field submit-span-2"><span data-submit-copy="logoImage">${esc(t('logoImage'))}</span><div class="submit-upload-zone submit-logo-upload" data-drop-zone="logo"><input class="submit-file-input" type="file" name="logo_file" accept="image/png,image/jpeg,image/webp,image/gif" data-logo-input><div class="submit-upload-empty" data-logo-empty><button type="button" class="submit-upload-plus" data-pick-logo aria-label="${esc(t('addLogo'))}">+</button><div><b data-submit-copy="addLogo">${esc(t('addLogo'))}</b><p data-submit-copy="dropLogo">${esc(t('dropLogo'))}</p></div></div><div class="submit-logo-selected" data-logo-selected hidden></div></div><em data-submit-copy="logoHelp">${esc(t('logoHelp'))}</em></div>
          <label class="submit-field"><span><span data-submit-copy="productName">${esc(t('productName'))}</span> <i>*</i></span><input required maxlength="60" name="name" data-submit-placeholder="namePlaceholder" placeholder="${esc(t('namePlaceholder'))}"><small><b data-submit-count="name">0</b> / 60</small></label>
          <label class="submit-field"><span><span data-submit-copy="tagline">${esc(t('tagline'))}</span> <i>*</i></span><input required maxlength="100" name="tag" data-submit-placeholder="tagPlaceholder" placeholder="${esc(t('tagPlaceholder'))}"><small><b data-submit-count="tag">0</b> / 100</small></label>
          <label class="submit-field"><span><span data-submit-copy="category">${esc(t('category'))}</span> <i>*</i></span><select required name="cat"><option value="" selected disabled data-submit-copy="categoryPlaceholder">${esc(t('categoryPlaceholder'))}</option>${categoryOptions}</select></label>
          <div class="submit-field"><span><span data-submit-copy="platform">${esc(t('platform'))}</span> <i>*</i></span><input type="hidden" name="platform" value=""><div class="submit-segments submit-platform-segments">${choice('platform','web','web')}${choice('platform','app','app')}</div></div>
          <div class="submit-field submit-span-2"><span><span data-submit-copy="status">${esc(t('status'))}</span> <i>*</i></span><input type="hidden" name="release_stage" value=""><div class="submit-segments submit-status-segments">${choice('release_stage','released','released','data-status-dot="true"')}${choice('release_stage','early_access','beta')}${choice('release_stage','in_development','development')}${choice('release_stage','in_development','idea','data-status-label="idea"')}</div></div>
          <div class="submit-field submit-span-2"><span data-submit-copy="projectImages">${esc(t('projectImages'))}</span><div class="submit-project-upload" data-drop-zone="projects"><input class="submit-file-input" type="file" name="project_images" accept="image/png,image/jpeg,image/webp,image/gif" multiple data-project-input><div class="submit-project-list" data-project-list></div><button type="button" class="submit-project-add" data-pick-project><b>+</b><span data-submit-copy="addProjectImage">${esc(t('addProjectImage'))}</span><small data-submit-copy="dropProjectImages">${esc(t('dropProjectImages'))}</small></button></div><em data-submit-copy="projectImagesHelp">${esc(t('projectImagesHelp'))}</em></div>
          <label class="submit-field submit-span-2"><span><span data-submit-copy="description">${esc(t('description'))}</span> <i>*</i></span><div class="submit-editor"><div class="submit-editor-toolbar" aria-hidden="true"><b>B</b><i>I</i><u>U</u><span>≡</span><span>☷</span><span>↗</span></div><textarea required maxlength="2000" name="problem" data-submit-placeholder="descriptionPlaceholder" placeholder="${esc(t('descriptionPlaceholder'))}"></textarea><small><b data-submit-count="problem">0</b> / 2000</small></div></label>
          <label class="submit-field"><span data-submit-copy="audience">${esc(t('audience'))}</span><input maxlength="120" name="audience" data-submit-placeholder="audiencePlaceholder" placeholder="${esc(t('audiencePlaceholder'))}"><small><b data-submit-count="audience">0</b> / 120</small></label>
          <label class="submit-field"><span data-submit-copy="problem">${esc(t('problem'))}</span><input maxlength="120" name="solve" data-submit-placeholder="problemPlaceholder" placeholder="${esc(t('problemPlaceholder'))}"><small><b data-submit-count="solve">0</b> / 120</small></label>
          <label class="submit-field submit-span-2"><span data-submit-copy="tags">${esc(t('tags'))}</span><input name="tags" data-submit-placeholder="tagsPlaceholder" placeholder="${esc(t('tagsPlaceholder'))}"></label>
        </div></section>
        <section class="submit-step-panel" data-submit-step="2" hidden>${text('h2','details')}<div class="submit-field-grid">
          <label class="submit-field submit-span-2"><span><span data-submit-copy="website">${esc(t('website'))}</span> <i>*</i></span><input required type="url" name="url" placeholder="https://vibeguys.app"></label>
          <label class="submit-field"><span><span data-submit-copy="creator">${esc(t('creator'))}</span> <i>*</i></span><input required name="maker" data-submit-placeholder="creatorPlaceholder" placeholder="${esc(t('creatorPlaceholder'))}"></label>
          <label class="submit-field"><span data-submit-copy="launchDate">${esc(t('launchDate'))}</span><input type="date" name="launch_date"></label>
          <label class="submit-field"><span data-submit-copy="languages">${esc(t('languages'))}</span><input name="languages" data-submit-placeholder="languagePlaceholder" placeholder="${esc(t('languagePlaceholder'))}"></label>
          <label class="submit-field"><span data-submit-copy="contact">${esc(t('contact'))}</span><input type="email" name="contact_email" placeholder="hello@vibeguys.com"></label>
          <label class="submit-field"><span data-submit-copy="docs">${esc(t('docs'))}</span><input type="url" name="docs_url" placeholder="https://"></label><label class="submit-field"><span data-submit-copy="demo">${esc(t('demo'))}</span><input type="url" name="demo_url" placeholder="https://"></label><label class="submit-field submit-span-2"><span data-submit-copy="github">${esc(t('github'))}</span><input type="url" name="github_url" placeholder="https://github.com/"></label>
        </div></section>
        <section class="submit-step-panel" data-submit-step="3" hidden>${text('h2','review')}<p class="submit-review-intro" data-submit-copy="reviewIntro">${esc(t('reviewIntro'))}</p><dl class="submit-review-list"><div><dt data-submit-copy="reviewProduct">${esc(t('reviewProduct'))}</dt><dd data-submit-review="name">—</dd></div><div><dt data-submit-copy="reviewType">${esc(t('reviewType'))}</dt><dd data-submit-review="platform">—</dd></div><div><dt data-submit-copy="reviewUrl">${esc(t('reviewUrl'))}</dt><dd data-submit-review="url">—</dd></div><div><dt data-submit-copy="reviewMedia">${esc(t('reviewMedia'))}</dt><dd data-submit-review="screenshots">0</dd></div></dl><label class="submit-legal"><input required type="checkbox" name="terms_accepted"><span data-submit-copy="agreement">${esc(t('agreement'))}</span></label></section>
        <div class="submit-form-actions"><button type="button" class="submit-back" data-submit-prev hidden><span data-submit-copy="previous">${esc(t('previous'))}</span></button><button type="button" class="submit-next" data-submit-primary data-mode="next"><span data-submit-primary-label>${esc(t('next'))}</span><b aria-hidden="true">→</b></button></div>
      </form>
      <section class="submit-preview-column" aria-live="polite"><header><h2 data-submit-copy="preview">${esc(t('preview'))}</h2><p data-submit-copy="previewHelp">${esc(t('previewHelp'))}</p></header><article class="submit-preview-card">
        <div class="submit-preview-product"><div class="submit-preview-logo" data-preview-logo aria-hidden="true"><span>+</span></div><div><h3 data-preview-name></h3><p data-preview-tagline></p><div class="submit-preview-tags" data-preview-tags hidden></div></div><a href="#" data-preview-visit hidden><span data-submit-copy="visit">${esc(t('visit'))}</span> <b aria-hidden="true">↗</b></a></div>
        <p class="submit-preview-description" data-preview-description></p><div class="submit-preview-shots" data-preview-shots><div class="submit-preview-shots-empty"><b>+</b><span data-submit-copy="emptyImages">${esc(t('emptyImages'))}</span></div></div>
        <div class="submit-preview-meta"><span data-preview-meta="maker" hidden><i aria-hidden="true">♙</i><b data-preview-maker></b></span><span data-preview-meta="date" hidden><i aria-hidden="true">□</i><b data-preview-date></b></span><span data-preview-meta="languages" hidden><i aria-hidden="true">◎</i><b data-preview-languages></b></span></div>
        <div class="submit-preview-bottom"><section><h4 data-submit-copy="features">${esc(t('features'))}</h4><ul data-preview-features></ul><p class="submit-preview-empty-copy" data-preview-features-empty data-submit-copy="emptyFeatures">${esc(t('emptyFeatures'))}</p></section><aside><h4 data-submit-copy="links">${esc(t('links'))}</h4>${[['websiteLink','website'],['docsLink','docs'],['demoLink','demo'],['githubLink','github']].map(([label,key])=>`<p class="is-empty"><b data-submit-copy="${label}">${esc(t(label))}</b><span data-preview-link="${key}"></span><i aria-hidden="true">↗</i></p>`).join('')}</aside></div>
      </article><footer><span class="submit-security-icon" aria-hidden="true"></span><p data-submit-copy="security">${esc(t('security'))}</p></footer></section>
      <aside class="submit-guide-column"><section class="submit-guide-card"><h2 data-submit-copy="guide">${esc(t('guide'))}</h2>${[['info','guideAccuracy','guideAccuracyBody'],['shot','guideShots','guideShotsBody'],['link','guideLinks','guideLinksBody'],['review','guideReview','guideReviewBody']].map(([icon,title,body])=>`<article><span class="submit-guide-icon ${icon}" aria-hidden="true"></span><div><h3 data-submit-copy="${title}">${esc(t(title))}</h3><p data-submit-copy="${body}">${esc(t(body))}</p></div></article>`).join('')}</section><section class="submit-help-card"><h2 data-submit-copy="help">${esc(t('help'))}</h2><p data-submit-copy="helpBody">${esc(t('helpBody'))}</p><a href="LEGAL_NOTICE.md" target="_blank" rel="noreferrer"><span data-submit-copy="openGuide">${esc(t('openGuide'))}</span> <b>↗</b></a><small>contact@vibeguys.com</small></section></aside>
    </div></section>`;
    wire(host);syncPreview();setStep(1,false);
  }

  function setStep(next,scroll=true){currentStep=Math.max(1,Math.min(3,next));const page=currentHost?.querySelector('.submit-page');if(!page)return;page.querySelectorAll('[data-submit-step]').forEach(panel=>{const visible=Number(panel.dataset.submitStep)===currentStep;panel.hidden=!visible;panel.querySelectorAll('input,select,textarea').forEach(field=>{field.disabled=currentStep<3&&!visible})});page.querySelectorAll('[data-submit-step-indicator]').forEach(item=>{const index=Number(item.dataset.submitStepIndicator);item.classList.toggle('active',index===currentStep);item.classList.toggle('complete',index<currentStep)});page.querySelector('[data-submit-prev]').hidden=currentStep===1;const primary=page.querySelector('[data-submit-primary]');const final=currentStep===3;primary.type=final?'submit':'button';primary.dataset.mode=final?'submit':'next';primary.querySelector('[data-submit-primary-label]').textContent=t(final?'submit':'next');if(final)syncReview();if(scroll)page.querySelector('.submit-form-column')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function validateStep(){const panel=currentHost?.querySelector(`[data-submit-step="${currentStep}"]`);if(!panel)return true;for(const field of panel.querySelectorAll('input[required],select[required],textarea[required]')){if(!field.checkValidity()){field.reportValidity();return false}}if(currentStep===1){const form=currentHost.querySelector('#submit-form');if(!form.elements.platform.value||!form.elements.release_stage.value){alert(t('choiceRequired'));return false}}return true}
  function syncReview(){const form=currentHost?.querySelector('#submit-form');if(!form)return;const platform=form.elements.platform.value;const values={name:form.elements.name.value||'—',platform:platform?(platform==='both'?t('both'):t(platform)):'—',url:form.elements.url.value||'—',screenshots:String(projectFiles.length)};Object.entries(values).forEach(([key,value])=>{const node=form.querySelector(`[data-submit-review="${key}"]`);if(node)node.textContent=value})}
  function syncPreview(){const page=currentHost?.querySelector('.submit-page');const form=page?.querySelector('#submit-form');if(!form)return;const value=name=>String(form.elements[name]?.value||'').trim();const set=(selector,next)=>{const node=page.querySelector(selector);if(node){node.textContent=next;node.dataset.empty=next?'false':'true'}};set('[data-preview-name]',value('name'));set('[data-preview-tagline]',value('tag'));set('[data-preview-description]',value('problem'));set('[data-preview-maker]',value('maker'));set('[data-preview-languages]',value('languages'));set('[data-preview-date]',value('launch_date')?value('launch_date').replaceAll('-','.'):'');['maker','date','languages'].forEach(key=>{const item=page.querySelector(`[data-preview-meta="${key}"]`);if(item)item.hidden=!item.querySelector('b')?.textContent});const platform=value('platform');const category=categories.find(item=>item[0]===value('cat'));const statusKey=form.dataset.releaseLabel||({released:'released',early_access:'beta',in_development:'development'}[value('release_stage')]||'');const chips=[];if(platform)chips.push(platform==='both'?'WEB + APP':platform.toUpperCase());if(category)chips.push(isKo()?category[1]:category[2]);if(statusKey)chips.push(t(statusKey));value('tags').split(',').map(tag=>tag.trim()).filter(Boolean).slice(0,2).forEach(tag=>chips.push(tag));const tagHost=page.querySelector('[data-preview-tags]');tagHost.hidden=!chips.length;tagHost.innerHTML=chips.map(chip=>`<span>${esc(chip)}</span>`).join('');const url=value('url');const visit=page.querySelector('[data-preview-visit]');visit.href=url||'#';visit.hidden=!url;visit.dataset.enabled=url?'true':'false';const linkValues={website:url,docs:value('docs_url'),demo:value('demo_url'),github:value('github_url')};Object.entries(linkValues).forEach(([key,link])=>{const node=page.querySelector(`[data-preview-link="${key}"]`);if(node){node.textContent=link.replace(/^https?:\/\//,'');node.closest('p')?.classList.toggle('is-empty',!link)}});const features=[value('audience'),value('solve'),...value('tags').split(',').map(item=>item.trim())].filter(Boolean).slice(0,5);page.querySelector('[data-preview-features]').innerHTML=features.map(item=>`<li><i>✓</i><span>${esc(item)}</span></li>`).join('');page.querySelector('[data-preview-features-empty]').hidden=features.length>0;page.querySelectorAll('[data-submit-count]').forEach(counter=>{counter.textContent=String(form.elements[counter.dataset.submitCount]?.value.length||0)});syncReview()}
  function validImages(files){const accepted=[];let rejected=false;[...files].forEach(file=>{if(file&&allowedImageTypes.has(file.type)&&file.size<=maxImageBytes)accepted.push(file);else rejected=true});if(rejected)alert(t('invalidImage'));return accepted}
  function assignFiles(input,files){const transfer=new DataTransfer();files.forEach(file=>transfer.items.add(file));input.files=transfer.files}
  function setLogo(file){const input=currentHost.querySelector('[data-logo-input]');const accepted=validImages(file?[file]:[]);logoFile=accepted[0]||null;assignFiles(input,logoFile?[logoFile]:[]);renderMedia()}
  function setProjectFiles(files,append=false){const incoming=validImages(files);const merged=append?[...projectFiles,...incoming]:incoming;const unique=merged.filter((file,index,list)=>list.findIndex(item=>item.name===file.name&&item.size===file.size&&item.lastModified===file.lastModified)===index);if(unique.length>6)alert(t('imageLimit'));projectFiles=unique.slice(0,6);assignFiles(currentHost.querySelector('[data-project-input]'),projectFiles);renderMedia()}
  function renderMedia(){const page=currentHost?.querySelector('.submit-page');if(!page)return;if(logoObjectUrl)URL.revokeObjectURL(logoObjectUrl);projectObjectUrls.forEach(url=>URL.revokeObjectURL(url));logoObjectUrl='';projectObjectUrls=[];const empty=page.querySelector('[data-logo-empty]'),selected=page.querySelector('[data-logo-selected]');empty.hidden=Boolean(logoFile);selected.hidden=!logoFile;if(logoFile){logoObjectUrl=URL.createObjectURL(logoFile);selected.innerHTML=`<img src="${logoObjectUrl}" alt=""><div><b>${esc(logoFile.name)}</b><small>${(logoFile.size/1024/1024).toFixed(1)} MB</small></div><button type="button" data-remove-logo aria-label="${esc(t('remove'))}">×</button>`}else selected.innerHTML='';const list=page.querySelector('[data-project-list]');projectObjectUrls=projectFiles.map(file=>URL.createObjectURL(file));list.innerHTML=projectFiles.map((file,index)=>`<article><img src="${projectObjectUrls[index]}" alt=""><button type="button" data-remove-project="${index}" aria-label="${esc(t('remove'))}">×</button><span>${esc(file.name)}</span></article>`).join('');const previewLogo=page.querySelector('[data-preview-logo]');previewLogo.innerHTML=logoObjectUrl?`<img src="${logoObjectUrl}" alt="">`:'<span aria-hidden="true">+</span>';const shots=page.querySelector('[data-preview-shots]');shots.classList.toggle('has-images',projectObjectUrls.length>0);shots.innerHTML=projectObjectUrls.length?projectObjectUrls.map(url=>`<img src="${url}" alt="">`).join(''):`<div class="submit-preview-shots-empty"><b>+</b><span data-submit-copy="emptyImages">${esc(t('emptyImages'))}</span></div>`;syncReview()}
  function dropWire(zone,type){['dragenter','dragover'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',event=>{const files=event.dataTransfer?.files||[];if(type==='logo')setLogo(files[0]);else setProjectFiles(files,true)})}
  function localize(){const page=currentHost?.querySelector('.submit-page');if(!page)return;page.querySelectorAll('[data-submit-copy]').forEach(node=>{const key=node.dataset.submitCopy;if(copy[key])node.textContent=t(key)});page.querySelectorAll('[data-submit-placeholder]').forEach(node=>{node.placeholder=t(node.dataset.submitPlaceholder)});const categorySelect=page.querySelector('[name="cat"]');if(categorySelect){[...categorySelect.options].slice(1).forEach((option,index)=>{const category=categories[index];if(category)option.textContent=isKo()?category[1]:category[2]})}renderMedia();syncPreview();setStep(currentStep,false)}
  function wire(host){
    const form=host.querySelector('#submit-form');
    form.addEventListener('input',syncPreview);form.addEventListener('change',syncPreview);
    form.addEventListener('reset',()=>setTimeout(()=>{logoFile=null;projectFiles=[];delete form.dataset.releaseLabel;host.querySelectorAll('[data-submit-choice]').forEach(item=>item.classList.remove('active'));renderMedia();syncPreview();setStep(1,false)},0));
    host.querySelector('[data-preview-visit]')?.addEventListener('click',event=>{if(event.currentTarget.dataset.enabled!=='true')event.preventDefault()});
    host.querySelectorAll('[data-submit-choice]').forEach(button=>button.addEventListener('click',()=>{
      const name=button.dataset.submitChoice;
      if(name==='platform'){
        button.classList.toggle('active');
        const selected=[...host.querySelectorAll('[data-submit-choice="platform"].active')].map(item=>item.dataset.value);
        form.elements.platform.value=selected.length===2?'both':selected[0]||'';
      }else{
        form.elements[name].value=button.dataset.value;
        if(name==='release_stage')form.dataset.releaseLabel=button.dataset.statusLabel||({released:'released',early_access:'beta',in_development:'development'}[button.dataset.value]||'');
        host.querySelectorAll(`[data-submit-choice="${name}"]`).forEach(item=>item.classList.toggle('active',item===button));
      }
      syncPreview();
    }));
    host.querySelector('[data-submit-primary]').addEventListener('click',event=>{if(event.currentTarget.dataset.mode==='next'&&validateStep())setStep(currentStep+1)});host.querySelector('[data-submit-prev]').addEventListener('click',()=>setStep(currentStep-1));
    host.querySelector('[data-pick-logo]').addEventListener('click',()=>host.querySelector('[data-logo-input]').click());host.querySelector('[data-pick-project]').addEventListener('click',()=>host.querySelector('[data-project-input]').click());
    host.querySelector('[data-logo-input]').addEventListener('change',event=>setLogo(event.target.files[0]));host.querySelector('[data-project-input]').addEventListener('change',event=>setProjectFiles(event.target.files,true));
    host.addEventListener('click',event=>{if(event.target.closest('[data-remove-logo]'))setLogo(null);const remove=event.target.closest('[data-remove-project]');if(remove){projectFiles.splice(Number(remove.dataset.removeProject),1);setProjectFiles(projectFiles)}});
    dropWire(host.querySelector('[data-drop-zone="logo"]'),'logo');dropWire(host.querySelector('[data-drop-zone="projects"]'),'projects');
  }
  document.addEventListener('submit',event=>{if(event.target.id!=='submit-form'||!currentHost?.querySelector('.submit-page')||currentStep===3)return;event.preventDefault();event.stopImmediatePropagation();if(validateStep())setStep(currentStep+1)},true);
  document.addEventListener('click',event=>{if(event.target.closest('[data-action="language"]'))setTimeout(localize,0)});
  window.VibeGuysSubmit={render};
})();
